@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/Sub-Talisman/project>
	deps:runtime-requirement         [ deps:on "Attribute::Handlers 0.79"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "namespace::clean"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "perl 5.008"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "Sub::Util"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ].

