# This file provides instructions for packaging.

`Sub-Talisman`
	perl_version_from m`Sub::Talisman`;
	version_from      m`Sub::Talisman`;
	readme_from       m`Sub::Talisman`;
	test_requires     p`Test::More 0.61`;
	requires          p`namespace::clean`;
	requires          p`Scalar::Does 0.002`;
	requires          p`Sub::Identify`;
	requires          p`Sub::Name`;
.

